### ISSUE TITLE
Changing letters on FoxServerSetup class to unicode form

### ISSUE THREAD

**Issue by BaturayOnural** [ProjectTilki/Tilki#1]
#The letters in MainClient and FoxServerSetup class, should be written as Turkish language - Unicode form.

**Comment by BaturayOnural** [comment]
MainClient also has same problem

**Comment by RootG** [comment]
@BaturayOnural Make sure you are using the latest version, if so I need more detailed description of the issue. Since Windows users are affected, I am not able to reproduce the issue on my Linux system.
